/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicShortenRouteImport } from './routes/api/public/shorten'
import { Route as ApiPublicUrlsRouteImport } from './routes/api/public/urls'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShortenRoute = ApiPublicShortenRouteImport.update({
  id: '/api/public/shorten',
  path: '/api/public/shorten',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUrlsRoute = ApiPublicUrlsRouteImport.update({
  id: '/api/public/urls',
  path: '/api/public/urls',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/shorten': typeof ApiPublicShortenRoute
  '/api/public/urls': typeof ApiPublicUrlsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/shorten': typeof ApiPublicShortenRoute
  '/api/public/urls': typeof ApiPublicUrlsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/shorten': typeof ApiPublicShortenRoute
  '/api/public/urls': typeof ApiPublicUrlsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/shorten' | '/api/public/urls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/shorten' | '/api/public/urls'
  id: '__root__' | '/' | '/api/public/shorten' | '/api/public/urls'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicShortenRoute: typeof ApiPublicShortenRoute
  ApiPublicUrlsRoute: typeof ApiPublicUrlsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shorten': {
      id: '/api/public/shorten'
      path: '/api/public/shorten'
      fullPath: '/api/public/shorten'
      preLoaderRoute: typeof ApiPublicShortenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/urls': {
      id: '/api/public/urls'
      path: '/api/public/urls'
      fullPath: '/api/public/urls'
      preLoaderRoute: typeof ApiPublicUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicShortenRoute: ApiPublicShortenRoute,
  ApiPublicUrlsRoute: ApiPublicUrlsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
